import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: false,
  sourcemap: true,
  clean: false,
  target: 'esnext',
  outDir: 'dist',
  treeshake: true,
  external: [
    'dotenv',
    'fs',
    'path',
    'os',
    'crypto',
    'stream',
    'util',
    'events',
    'child_process',
    'readline',
    'process',
    'url',
    'http',
    'https',
    'net',
    'tls',
    'zlib',
    'assert',
    'buffer',
    'querystring',
    'string_decoder',
    'punycode',
    'domain',
    'dns',
    'dgram',
    'cluster',
    'v8',
    'vm',
    'perf_hooks',
    'async_hooks',
    'http2',
    'inspector',
    'trace_events',
    'worker_threads',
    'module',
    'tty',
    'constants',
    'sys',
    '_stream_duplex',
    '_stream_passthrough',
    '_stream_readable',
    '_stream_transform',
    '_stream_writable',
    'timers',
    'console',
    'repl',
    'diagnostics_channel',
    'wasi',
    'node:*',
    'zod',
    'pino',
    'pino-pretty',
  ],
});
